# Generated by Django 4.2.14 on 2026-07-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='tab_switch_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
