# Generated by Django 4.2.14 on 2026-07-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_tab_switch_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='auto_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='violation_reason',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
