# Generated by Django 4.2.14 on 2026-07-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
